# Generated by Django 3.0.3 on 2020-02-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='user',
        ),
    ]
