# Generated by Django 3.0.3 on 2020-02-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200212_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
