# Generated by Django 3.0.3 on 2020-02-12 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200212_2045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0004_meetings_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetings',
            new_name='Meeting',
        ),
    ]
