# Generated by Django 3.0.3 on 2020-02-14 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0005_auto_20200212_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
