# Generated by Django 3.0.3 on 2020-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_setmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmeeting',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
