# Generated by Django 3.0.3 on 2020-02-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20200214_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmeeting',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
