# Generated by Django 3.0.3 on 2020-02-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20200215_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmeeting',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
