# Generated by Django 3.0.3 on 2020-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_setmeeting_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmeeting',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
