# Generated by Django 3.0.3 on 2020-02-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_setmeeting_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmeeting',
            name='attended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
