# Generated by Django 3.0.3 on 2020-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
