# Generated by Django 3.0.3 on 2020-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='password',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
