# Generated by Django 3.0.3 on 2020-02-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200226_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrmUser',
        ),
    ]
