# Generated by Django 3.0.3 on 2020-02-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.BooleanField(default=False),
        ),
    ]
