# Generated by Django 3.0.3 on 2020-02-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='company_city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='country',
            new_name='company_country',
        ),
    ]
