# Generated by Django 3.0.3 on 2020-02-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200210_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
