# Generated by Django 3.0.3 on 2020-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200206_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
