# Generated by Django 3.0.3 on 2020-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200322_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='departement',
        ),
        migrations.AddField(
            model_name='contact',
            name='dep_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
