# Generated by Django 3.0.3 on 2020-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200207_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
