# Generated by Django 3.0.3 on 2020-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200323_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.AddField(
            model_name='company',
            name='client',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
