# Generated by Django 3.0.3 on 2020-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
