# Generated by Django 3.0.3 on 2020-03-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20200324_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
