# Generated by Django 3.0.3 on 2020-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20200324_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
    ]
