# Generated by Django 3.0.3 on 2020-03-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20200325_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
